### ISSUE TITLE
Glium 0.26.0-alpha3 does not compile with Glutin 0.22.0-alpha4/5

### ISSUE THREAD

**Issue by Speedy-Consoles** [glium/glium#1796]
In a fresh package, if you just put `glium = "0.26.0-alpha3"` as dependency in your Cargo.toml, it will give you this error:
```
error[E0004]: non-exhaustive patterns: `Err(FunctionUnavailable)` not covered
   --> [...]/glium-0.26.0-alpha3/src/backend/glutin/mod.rs:253:15
    |
253 |         match self.borrow().swap_buffers() {
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ pattern `Err(FunctionUnavailable)` not covered
    |
```
There is a new enum variant since Glutin 0.22.0-alpha4, that is not considered in Glium.

**Comment by est31** [comment]
Hmm that's weird, I've thought alpha releases are incompatible to each other... Maybe the requirement in Cargo.toml should be a `=` one...

PRs to port glium to the newer alpha release are welcome!

**Comment by est31** [comment]
(if there is no interest in doing a PR, I'll make one tomorrow anyway)

**Comment by Speedy-Consoles** [comment]
I'm not familiar enough with the code, to port it. Maybe `ContextError::FunctionUnavailable` should be forwarded into a a new variant `SwapBuffersError::FunctionUnavailable`. That depends on what
```
glutin/src/api/egl/mod.rs:694:

if !egl.SwapBuffersWithDamageKHR.is_loaded() {
    return Err(ContextError::FunctionUnavailable);
}
```
implies.

**Comment by est31** [comment]
> That depends on what `(*code*)` implies

Check how the `swap_buffers_with_damage_supported` function uses that same `is_loaded` function. So basically the error is `ContextError::SwapBuffersWithDamageUnsupported` or something like that. Anyways, it's only ever returned if you call `swap_buffers_with_damage` which we don't, so a panic like the other ones should be fine.
