### ISSUE TITLE
RawImage2D::from_rgba_reversed() example doesn't work with image 0.15.0

### ISSUE THREAD

**Issue by NiklasRosenstein** [glium/glium#1609]
Trying to follow this guide: https://github.com/glium/glium/blob/master/book/tuto-06-texture.md

This code does not compile, as image.into_raw() returns `std::vec::Vec` and not `&[u8]`.

```
  use std::io::Cursor;
  let image = image::load(Cursor::new(&include_bytes!("../data/alpha-512.png")[..]),
                          image::PNG).unwrap().to_rgba();
  let image_dimensions = image.dimensions();
  let image = glium::texture::RawImage2d::from_raw_rgba_reversed(image.into_raw(), image_dimensions);
```

Error message:

```
error[E0308]: mismatched types
  --> src\main.rs:52:66
   |
52 |   let image = glium::texture::RawImage2d::from_raw_rgba_reversed(image.into_raw(), image_dimensions);
   |                                                                  ^^^^^^^^^^^^^^^^ expected &[_], found struct `std::vec::Vec`
   |
   = note: expected type `&[_]`
              found type `std::vec::Vec<u8>`
   = help: try with `&image.into_raw()`

error: aborting due to previous error(s)

error: Could not compile `aixsponza-dilate`.
```

**Comment by tomaka** [comment]
I guess simply adding a `&` (ie. `&image.into_raw()`) should fix it.

**Comment by NiklasRosenstein** [comment]
@tomaka Yes, that worked! I also found out that `image.into_raw().as_slice()` works. I assume your suggested method is preferred?

**Comment by NiklasRosenstein** [comment]
Hm now that this line works, I get an error with this line:
```
let texture = glium::texture::Texture2d::new(&display, image).unwrap();
```

Error:

```
error[E0277]: the trait bound `&glium::Display: glium::backend::Facade` is not satisfied
  --> src\main.rs:66:17
   |
66 |   let texture = glium::texture::Texture2d::new(&display, image).unwrap();
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `glium::backend::Facade` is not implemented for `&glium::Display`
   |
   = help: the following implementations were found:
             <glium::Display as glium::backend::Facade>
   = note: required by `glium::Texture2d::new`
```

**Comment by tomaka** [comment]
My guess is that your `display` is probably already a `&Display`, so you're passing a `&&Display` to the function.

**Comment by NiklasRosenstein** [comment]
Right! Thank you again, that also helped me to understand Rust a bit better.
